name: ip-info
version: 0.1.0
summary: IP info
description: An app to show information about your IP address

confinement: strict
base: core18
grade: stable

slots:
  dbus-ip-info: # adjust accordingly to your app name
    interface: dbus
    bus: session
    name: org.bar.chekhov.ip_info # adjust accordingly to your app name and
    
apps:
  ip-info:
    command: ip_info
    extensions: [flutter-master] # Where "master" defines which Flutter channel to use for the build
    plugs:
    - network
    slots:
      - dbus-ip-info
parts:
  ip-info:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application
